[KR] translation of 10.1.md
Atcold/pytorch-Deep-Learning pull request #459
Opened 2020-08-16 18:40 UTC by Dohppak

2020-08-19 03:48 UTC, Atcold commented
@skyil7, please review and merge this. Thanks!

2020-08-19 05:42 UTC, skyil7 approved these changes

2020-08-19 05:42 UTC, skyil7 commented on docs/ko/week10/10-1.md
> +<b>Figure 2:</b> 라벨이있는 사용 가능한 이미지 분포의 변화
`라벨이있는` -> `라벨이 있는`
띄어쓰기 오류입니다!

2020-08-19 05:42 UTC, skyil7 commented on docs/ko/week10/10-1.md
> +## 자기 지도 학습이란 무엇입니까?
타이틀이니 조금 더 강하게 `자기 지도 학습이란 무엇인가?` 와 같은 번역은 어떨까요?

제안일 뿐이니 성훈님이 원하시는 데로 해주시기 바랍니다!

2020-08-19 05:46 UTC, skyil7 requested changes
Please Check the comments and update!

Thank you!

2020-08-23 21:21 UTC, Dohppak commented
리뷰를 바탕을 수정했습니다 감사합니다 :)

2020-08-25 04:42 UTC, skyil7 approved these changes

2020-08-25 04:42 UTC, merged

2020-08-30 07:36 UTC, Atcold commented
@skyil7, please don't merge edits to the `jekyllbook` submodule.

![image](https://user-images.githubusercontent.com/2119355/91653828-fde3f300-ea71-11ea-9fe0-1fc22b12b37c.png)

2020-08-30 12:46 UTC, skyil7 commented
@Atcold Oh, I missed it. Sorry T.T