[KR] Translation of 10-2.md
Atcold/pytorch-Deep-Learning pull request #477
Opened 2020-08-25 21:46 UTC by Dohppak

2020-08-30 07:35 UTC, Atcold commented
@skyil7, when you can, please have a look at this.

2020-08-30 12:55 UTC, skyil7 requested changes
merge 전에 `docs/jekyllbook` 파일의 변경 사항을 없애주셔야 합니다!

이외에 번역은 수정할 곳이 별로 없네요!! 정말 수고많으셨습니다. 감사합니다~

2020-08-30 12:55 UTC, skyil7 commented on docs/ko/week10/10-1.md
> +지난 10 년 동안 다양한 컴퓨터 비전 문제의 주요 성공 비결 중 하나는 이미지넷<sup>ImageNet</sup> 분류에 대해 지도 학습을 수행하여 시각적 표현을 학습하는 것이 었습니다. 그리고 이러한 학습 된 표현 또는 학습 된 모델 가중치를 대량의 레이블이 지정된 데이터를 사용할 수 없는 다른 컴퓨터 비전 작업에 대한 초기화 값으로 사용하였습니다.
`것이 었습니다` 띄어쓰기 오류입니다! `것이었습니다`로 수정해주세요~

2020-09-03 02:19 UTC, Atcold commented
Please, don't change the `jekyllbook` submodule.

2020-09-03 04:12 UTC, Dohppak commented
확인했습니다! sry, I will change!

2020-09-03 04:25 UTC, Dohppak commented
@skyil7 docs/jekyllbook을 revert 하고 review를 반영했습니다! 한번 확인해주시면 감사하겠습니다.

2020-09-03 06:16 UTC, Atcold requested changes
I still see this:

![image](https://user-images.githubusercontent.com/2119355/92078009-8a9cf280-ed8b-11ea-8b18-9b639779496d.png)

2020-09-03 07:07 UTC, skyil7 approved these changes

2020-09-03 07:09 UTC, skyil7 commented
jekyllbook 이 아직도 해결이 안되었네요 ㅠㅠ
혹시 해결이 잘 안되시면 다시 fork 하셔서 다시 pr을 해보시는 것도 좋을 것 같습니다.

2020-09-03 08:15 UTC, Dohppak commented
네! 다시 fork해서 pr하겠습니다 ㅠㅠ 혹시 이 PR은 Close할까요?

2020-09-03 08:17 UTC, Dohppak commented
@skyil7  네 ㅠㅠ 다시 fork해서 PR했습니다. 이 PR은 close할까요?

2020-09-03 08:57 UTC, skyil7 commented
네! 부탁드립니다~

2020-09-03 09:22 UTC, closed without merging

2020-09-06 18:40 UTC, Atcold commented
What happened here?