[TR] translation of 12-3.md
Atcold/pytorch-Deep-Learning pull request #485
Opened 2020-09-01 17:57 UTC by mevah

2020-09-03 02:32 UTC, Atcold requested changes
You need to update `docs/_config.yml`.

There are two files, the first one is in the wrong directory.
![image](https://user-images.githubusercontent.com/2119355/92064725-156df500-ed6c-11ea-8653-f95e661b2b4c.png)

2020-09-03 02:32 UTC, Atcold commented on docs/tr/week12/12-3.md
> +lang-ref: ch.12-3
`lang: tr` is missing.

2020-09-03 07:23 UTC, mevah commented
sorry, made changes.

2020-09-11 02:58 UTC, Atcold approved these changes
Fantastic! Thanks!

2020-09-11 02:58 UTC, merged