[TR] index.md update
Atcold/pytorch-Deep-Learning pull request #491
Opened 2020-09-03 12:55 UTC by mekici

Week 13 added tot he index

2020-09-11 02:45 UTC, Atcold requested changes
I'm confused. Isn't this PR supposed to update `index-tr.md` only?
What are these?

![image](https://user-images.githubusercontent.com/2119355/92847615-58a51500-f3b7-11ea-8fd3-b60fba341bbf.png)

2020-09-11 09:02 UTC, mekici commented
No, as I said in the previous mail, due to conflicted merge I removed the
fork and commits related to the translations also have gone with the fork.
So I translated the pages 7-11-13-14 again and pushed to the origin. It
contains both the translated pages and updates of index.md.

Murat
_________________________________________________



Dr. Murat EKİCİ, Ph.D.
Usak University
Faculty of Education
Department Of Computer Education and Instructional Technology, Office #329
USAK/TURKEY
T:  +90 276 221 2130 / 2179    F: +90 276 221 2131    Gsm: +90 532 067
88 15

Email: murat.ekici@usak.edu.tr
web: http://akbis.usak.edu.tr/Home/Index/murat.ekici
<http://akbis.usak.edu.tr/Home/Index/murat.ekici>





On Fri, Sep 11, 2020 at 5:45 AM Alfredo Canziani <notifications@github.com>
wrote:

> *@Atcold* requested changes on this pull request.
>
> I'm confused. Isn't this PR supposed to update index-tr.md only?
> What are these?
>
> [image: image]
> <https://user-images.githubusercontent.com/2119355/92847615-58a51500-f3b7-11ea-8fd3-b60fba341bbf.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Atcold/pytorch-Deep-Learning/pull/491#pullrequestreview-486437118>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADY7BD53R5MNAAG25IVDIT3SFGFOFANCNFSM4QUXQUCQ>
> .
>

2020-09-13 17:25 UTC, Atcold requested changes
I see, thanks.

You need to update `docs/_config.yml` as well.
The authorship is done by my script, using the `translator:` field. Please, remove the signatures.
Update the name of this PR to reflect the files you're adding.

2020-09-13 17:25 UTC, Atcold commented on docs/tr/week07/07.md
> +🇹🇷 muratekici
```suggestion

```

2020-09-13 17:25 UTC, Atcold commented on docs/tr/week11/11.md
> +
```suggestion

```

2020-09-13 17:25 UTC, Atcold commented on docs/tr/week13/13.md
> +
```suggestion

```

2020-09-13 17:25 UTC, Atcold commented on docs/tr/week14/14.md
> +🇹🇷 muratekici
```suggestion

```

2020-09-13 17:25 UTC, Atcold commented on docs/tr/week13/13.md
> +translation-date: 12 June 2020
```suggestion
translation-date: 12 Jun 2020
```

2020-09-13 17:25 UTC, Atcold commented on docs/tr/week11/11.md
> +translation-date: 12 June 2020
```suggestion
translation-date: 12 Jun 2020
```

2020-09-13 17:25 UTC, Atcold commented on docs/tr/week07/07.md
> +translation-date: 12 June 2020
```suggestion
translation-date: 12 Jun 2020
```

2020-09-13 17:25 UTC, Atcold commented on docs/tr/week14/14.md
> +translation-date: 12 June 2020
```suggestion
translation-date: 12 Jun 2020
```

2020-09-15 03:39 UTC, Atcold approved these changes
Great! Thanks!

2020-09-15 03:39 UTC, merged