[IT] translation week 11
Atcold/pytorch-Deep-Learning pull request #496
Opened 2020-09-04 15:30 UTC by fguiso

Done: 11.md and 11-1.md
Still to do: 11-2.md and 11-3.md

FYI: the website is displaying this as week 10 because the _config.yml file doesn't include a week 10 section yet

2020-09-06 18:52 UTC, Atcold requested changes
Great! Just a few edits.

2020-09-06 18:52 UTC, Atcold commented on docs/it/week11/11-1.md
> +title: Activation and loss functions (part 1)
Title translation is missing.

2020-09-06 18:52 UTC, Atcold commented on docs/it/week11/11-1.md
> +<!-- ## [Activation functions](https://www.youtube.com/watch?v=bj1fh3BvqSU&t=15s) -->
You removed the YouTube link.
Plz, add title translation and missing link.

2020-09-06 18:52 UTC, Atcold commented on docs/it/week11/11-1.md
> +translation-date: 15 Agosto 2020
`April` -> `Apr`.
`Agosto` -> `Aug`.

2020-09-06 18:52 UTC, Atcold commented on docs/it/week11/11.md
> +translation-date: 15 August 2020
```suggestion
translation-date: 15 Aug 2020
```

2020-09-07 22:56 UTC, fguiso commented
> Great! Just a few edits.

Fixed in the latest commit

2020-09-11 03:34 UTC, Atcold approved these changes
Yay! 🥳

2020-09-11 03:34 UTC, merged