[zh]12-3.md
Atcold/pytorch-Deep-Learning pull request #503
Opened 2020-09-05 14:24 UTC by Tangshengku

2020-09-11 02:49 UTC, Atcold requested changes

2020-09-11 02:49 UTC, Atcold commented on docs/zh/week12/12-3.md
> +title: Attention and the Transformer
Please, translate the title.

2020-09-15 06:03 UTC, JonathanSum commented on docs/zh/week12/12-3.md
> +title: Attention and the Transformer
注意力机制和Transformer

2020-09-17 04:32 UTC, Atcold commented
@Tangshengku, can you please update this PR with our suggestions?
You've removed your repository. I cannot edit your files.

2020-09-17 06:14 UTC, closed without merging