[KR] translation of 10-3.md
Atcold/pytorch-Deep-Learning pull request #505
Opened 2020-09-06 15:47 UTC by Dohppak

2020-09-11 02:56 UTC, Atcold commented
Thanks! You need to update `docs/_config.yml` as well.

2020-09-19 07:43 UTC, skyil7 requested changes

2020-09-19 07:43 UTC, skyil7 commented on docs/ko/week10/10-3.md
> +여기서 $s$는 속도<sup>signed speed</sup>를 나타내고 $\phi$는 음의 조종<sup>steering</sup> 각도를 나타냅니다.
`steering`의 번역에 대해, 조종보다 직관적인 표현이 없을까요? 예를들면, `핸들의 각도`나 `운전` 등 더 직관적으로 바꿔주시면 좋을 것 같습니다.

2020-09-19 07:43 UTC, skyil7 commented on docs/ko/week10/10-3.md
> +위와 같이 추상 다이어그램에서 두 블록은 훈련 될 두 네트워크입니다. $k$ 단계마다 "Trailer Truck Kinematics" 또는 우리가 에뮬레이터라고 부르는 것은 컨트롤러에서 생성 된 6차원의 상태 벡터와 조종 신호<sup>steering signal</sup>를 가져 와서 $k+1$ 단계의 새로운 6 차원 상태 벡터를 생성합니다.
`위와 같이 추상 다이어그램에서` 를 `위 추상도와 같이`로 바꿔주시면 좋을 것 같습니다!

2020-09-19 07:43 UTC, skyil7 commented on docs/ko/week10/10-3.md
> +위와 같이 추상 다이어그램에서 두 블록은 훈련 될 두 네트워크입니다. $k$ 단계마다 "Trailer Truck Kinematics" 또는 우리가 에뮬레이터라고 부르는 것은 컨트롤러에서 생성 된 6차원의 상태 벡터와 조종 신호<sup>steering signal</sup>를 가져 와서 $k+1$ 단계의 새로운 6 차원 상태 벡터를 생성합니다.
위에서 `steering` 번역을 바꾼다면 문서 전체에 `steering`을 수정해야겠군요!

2020-09-19 11:13 UTC, Dohppak commented on docs/ko/week10/10-3.md
> +위와 같이 추상 다이어그램에서 두 블록은 훈련 될 두 네트워크입니다. $k$ 단계마다 "Trailer Truck Kinematics" 또는 우리가 에뮬레이터라고 부르는 것은 컨트롤러에서 생성 된 6차원의 상태 벡터와 조종 신호<sup>steering signal</sup>를 가져 와서 $k+1$ 단계의 새로운 6 차원 상태 벡터를 생성합니다.
코멘트 감사합니다! 수정하도록 하겠습니다!

2020-09-21 05:15 UTC, Dohppak commented
@skyil7 수정내역 확인해주시면 감사하겠습니다!

2020-09-23 03:08 UTC, Atcold commented
@skyil7, what do you think?

2020-09-23 09:18 UTC, skyil7 approved these changes
수고많으셨습니다~ 머지하겠습니다!

2020-09-23 09:18 UTC, merged

2020-09-23 16:45 UTC, Atcold commented
Great! Thank you both!