[ES] Translation of 11-1.md
Atcold/pytorch-Deep-Learning pull request #529
Opened 2020-09-10 15:59 UTC by alceballosa

2020-09-11 04:44 UTC, Atcold requested changes
You need to update `docs/_config.yml` as well.

2020-09-11 04:44 UTC, Atcold commented on docs/es/week11/11-1.md
> +
Remove this.
```suggestion

```

2020-09-11 04:44 UTC, Atcold commented on docs/es/week11/11-1.md
> +title: Activation and loss functions (part 1)
Title needs a translation.

2020-09-11 04:44 UTC, Atcold commented on docs/es/week11/11-1.md
> +translation-lang: es
```suggestion
lang: es
```

2020-09-11 04:44 UTC, Atcold commented on docs/es/week11/11-1.md
> +date: 13 April 2020
```suggestion
date: 13 Apr 2020
```

2020-09-11 04:44 UTC, Atcold commented on docs/es/week11/11-1.md
> +translation-date: 09/10/2020
```suggestion
translation-date: 10 Sep 2020
```

2020-09-11 04:44 UTC, Atcold commented on docs/es/week11/11-1.md
> +translator: alceballosa
You may want to use your real name.

2020-09-11 04:58 UTC, alceballosa commented
Did all the changes you suggested, thank you professor!

2020-09-13 17:11 UTC, Atcold approved these changes
All is good now. I've updated `/docs/_config.yml` for you this time.

2020-09-13 17:12 UTC, merged