translate 06-2.md
Atcold/pytorch-Deep-Learning pull request #534
Opened 2020-09-12 01:01 UTC by AliEl-01

translation of 006-2.md , and also creating a folder call week06 to manage and organize all week06 files

2020-09-13 17:33 UTC, Atcold requested changes
A few issues. See below.

2020-09-13 17:33 UTC, Atcold commented on docs/ar/week06/06-2.md
> +date: 2 March 2020
What happened here? There is no header, the title is not translated, missing many fields.
Please, update.

2020-09-13 17:33 UTC, Atcold commented on docs/ar/week06/06.md
> +lang-ref: ch.06
`lang: ar` is missing.

2020-09-13 17:33 UTC, Atcold commented on docs/_config.yml
> +        - path: ar/week06/06-1.md
`06-2` is missing.

2020-09-13 22:24 UTC, AliEl-01 commented
is everythings 0k now !!!

2020-09-14 20:28 UTC, closed without merging

2020-09-15 03:42 UTC, Atcold commented
Why did you close this PR? I'm confused.

2020-09-15 13:55 UTC, AliEl-01 commented
I did another one with some updated stuff!😕

2020-09-17 04:34 UTC, Atcold commented
A PR keeps been updated if you push new commits.
You don't need to create a new one.