[KR] Translation of 13-1.md
Atcold/pytorch-Deep-Learning pull request #538
Opened 2020-09-13 12:02 UTC by shc443

2020-09-13 20:12 UTC, Atcold commented
@skyil7, please review.

2020-09-19 08:03 UTC, skyil7 requested changes
번역 수고하셨습니다. 리뷰 확인 부탁드립니다~

2020-09-19 08:03 UTC, skyil7 commented on docs/ko/week13/13-1.md
> +* **집약적<sup>Local</sup>** 신경망에서의 뉴런은 신경망 전체의 계층이 아닌 오직 인접한 계층들하고만 연결되어있다. 이를 집약적 수용영역 가정<sup></sup>이라고 부른다.
`수용영역 가정`뒤의 `<sup>` 태그 안에 내용이 없습니다. 내용을 추가하거나 태그를 지워주세요!

2020-09-19 08:03 UTC, skyil7 commented on docs/ko/week13/13-1.md
> +* **계층적<sup>Hierarchical</sup>** 저레벨 특징들은 모여서 중간레벨 특징을 이루고, 이 중간레벨 특징들이 계속해서 모여 더욱더 높은 레벨의 특징<sup></sup>들을 이룬다. 예로 시각표현을 들 수 있다.
위와 같이, `특징`뒤의 `<sup>`태그 수정바랍니다!

2020-09-19 08:03 UTC, skyil7 commented on docs/ko/week13/13-1.md
> +**2. 합성곱은 합성적 구조를 활용한다.**
위와 번역을 통일하여, `compositional`을 `구성적`으로 번역해주시면 좋을 것 같습니다!

2020-09-19 08:03 UTC, skyil7 commented on docs/ko/week13/13-1.md
> +* 이미지, 부피, 비디오는 각각 2D, 3D, 2D + 1 유클리드<sup>Euclidean</sup>의 정의역에 펼쳐져 있으며, 각 픽셀은 빨강, 초록, 파랑값의 벡터에 의해 표현된다.
`Euclidean domains`는 유클라드 공간을 의미하는 것이므로, 둘을 함께 `유클라드 정의역`으로 번역하고 이 뒤에 `<sup>`태그로 `Euclidean domains`을 넣어주면 더 이해하기 쉬워 보일 것 같습니다.

2020-09-19 08:03 UTC, skyil7 commented on docs/ko/week13/13-1.md
> +  <b>Fig. 5</b>: 순차<sup></sup>는 하나의 차원을 가진다.
`<sup>`태그가 비어있습니다.

2020-09-23 01:53 UTC, Atcold commented
@shc443 any update?

2020-09-23 14:54 UTC, shc443 commented
Hello Alf,

How are you? Thank you for the last week's meeting! I truly enjoyed talking
to you.

For the translation project, I just edited 13-1.md and uploaded 13-2.md. I
will upload the 13-3.md by tomorrow.

Hope you have a good rest of your day!

Best,
Kevin Choi
ᐧ

On Tue, Sep 22, 2020 at 9:53 PM Alfredo Canziani <notifications@github.com>
wrote:

> @shc443
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shc443&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=RT9SnvKO27VjQOWstLgUE5PPSiM6cMYGD_ePoJ3AgKA&s=unqBqEy9fk36JDOtAk48F5z5XlJrBaYfADJHCIyw_Zo&e=>
> any update?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Atcold_pytorch-2DDeep-2DLearning_pull_538-23issuecomment-2D697074681&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=RT9SnvKO27VjQOWstLgUE5PPSiM6cMYGD_ePoJ3AgKA&s=t48I74huq1CYT1rslxXlkvdMH0nGdTlWjmOCzbVdL7E&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHIZPADXPA3UHTPF2XOQ7J3SHFILDANCNFSM4RKT3PLA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=RT9SnvKO27VjQOWstLgUE5PPSiM6cMYGD_ePoJ3AgKA&s=W9vLaKL6uBJk9HC0LcIRWewyVX3B4GD5nK_yA70R36M&e=>
> .
>

2020-09-25 08:06 UTC, skyil7 approved these changes
리뷰 완료했습니다. 수고하셨습니다!

2020-09-25 08:07 UTC, merged

2020-09-26 03:49 UTC, Atcold commented
Great! Thanks!