[zh] translation of 13-2 and fixing 10-1
Atcold/pytorch-Deep-Learning pull request #562
Opened 2020-09-17 08:01 UTC by JonathanSum

2020-09-17 08:33 UTC, JonathanSum commented
![image](https://user-images.githubusercontent.com/21982975/93445070-d22b8000-f85b-11ea-8ea4-3c2c17d59abc.png)
I guess my vscode added for me?

2020-09-17 20:30 UTC, Atcold requested changes

2020-09-17 20:30 UTC, Atcold commented on docs/zh/week13/13-2.md
> +lang-ref: ch.13-2
`lang: zh`, `translator:`, and `translation-date:` are missing

2020-09-18 02:35 UTC, Atcold approved these changes

2020-09-18 02:35 UTC, merged

2020-09-18 02:35 UTC, Atcold commented
Thanks!