[EN] Fixed formula in English documents for chapter 13-3, Notation section.
Atcold/pytorch-Deep-Learning pull request #576
Opened 2020-09-19 02:31 UTC by xcastilla

The formula wasn't correctly rendered:
Before fix:
<img width="785" alt="Screen Shot 2020-09-19 at 11 16 45" src="https://user-images.githubusercontent.com/11987768/93657196-67509380-fa6b-11ea-9dce-4ccde2cea261.png">
After fix:
<img width="746" alt="Screen Shot 2020-09-19 at 11 17 28" src="https://user-images.githubusercontent.com/11987768/93657194-64ee3980-fa6b-11ea-81a7-c6704f98df3e.png">

I haven't checked the rest of the translations, but since the English one wasn't fixed maybe the rest do have this problem as well.

@Atcold

2020-09-19 02:34 UTC, Atcold requested changes
`j` should be left outside the bold.
Also, add "Close #563" to your commit message, so that you can close the issue automatically.

2020-09-19 02:35 UTC, Atcold requested changes
Here, try this.

2020-09-19 02:35 UTC, Atcold commented on docs/en/week13/13-3.md
> +We also have multiple vertices $v_{j}$, which is comprised of $\boldsymbol{x_{j}}$ and $\boldsymbol{h_{j}}$.
```suggestion
We also have multiple vertices $v_{j}$, which is comprised of $\boldsymbol{x}\_j$ and $\boldsymbol{h}\_j$.
```

2020-09-19 02:36 UTC, Atcold commented
You can tell the `_` is triggering the italic.

![image](https://user-images.githubusercontent.com/2119355/93657268-713cad00-f9ff-11ea-88ee-586816ae61d5.png)

2020-09-19 02:42 UTC, xcastilla commented
My bad, I didn't see the open issue. I commited the requested change.

2020-09-19 02:47 UTC, Atcold reviewed
Did you try running the website locally? Did it fix the issue?

2020-09-19 02:55 UTC, xcastilla commented
This is what the rendered version looks like after applying your suggestion. The subscript has been left outside the bold correctly.
<img width="727" alt="Screen Shot 2020-09-19 at 11 50 09" src="https://user-images.githubusercontent.com/11987768/93657595-ef846800-fa6e-11ea-839e-78d009c6332e.png">

2020-09-23 01:42 UTC, Atcold approved these changes
Great! Thanks!

2020-09-23 01:42 UTC, merged

2020-09-23 01:45 UTC, Atcold commented
@xcastilla, can we fix this for all the other languages as well? Thanks!