[ZH] Translate 14-1.md
Atcold/pytorch-Deep-Learning pull request #580
Opened 2020-09-19 05:32 UTC by titusjgr

2020-09-23 01:48 UTC, Atcold requested changes
You need to update `docs/_config.yml` as well.

2020-09-23 01:48 UTC, Atcold commented on docs/zh/week14/14-1.md
> +
```suggestion

```

2020-09-23 01:48 UTC, Atcold commented on docs/zh/week14/14-1.md
> +lang-ref: ch.14-1
```suggestion
lang-ref: ch.14-1
lang: zh
```

2020-09-24 12:59 UTC, titusjgr commented
I made the changes accordingly.

2020-09-26 03:46 UTC, Atcold approved these changes
Thanks!

2020-09-26 03:47 UTC, merged