[AR]week3-2 edit visual comments for rendering
Atcold/pytorch-Deep-Learning pull request #586
Opened 2020-09-19 09:23 UTC by ElJAZRY

2020-09-19 12:31 UTC, AliEl-01 reviewed
actually I don’t know why you don’t delete the English text. Personally, when I check and confirm the translation, I delete the English text. Please, if there is a valid reason for that tell me 🙏

2020-09-19 12:41 UTC, ElJAZRY commented
No, you should keep the English text commented  in the same file, don't delete it.

2020-09-23 02:13 UTC, Atcold approved these changes
Thanks!

2020-09-27 13:40 UTC, ElJAZRY commented
[AR] week03-03

2020-09-27 13:44 UTC, ElJAZRY commented
[AR] week03-03

2020-09-30 01:06 UTC, Atcold reviewed
Thanks. A few edits, as shown below, are necessary.
Also, you need to update `docs/_config.yml`.

2020-09-30 01:06 UTC, Atcold commented on docs/ar/week03/03-2.md
> +>>>>>>> 86fa5454e8420df3a360b1cba1671ec8641ae2ab
What is this supposed to be?

2020-09-30 01:06 UTC, Atcold commented on docs/ar/week03/03-3.md
> +----->
Header is missing.

2020-09-30 01:06 UTC, Atcold commented on docs/ar/week03/03-3.md
> +title: Properties of natural signals
The title is not translated.

2020-09-30 01:06 UTC, Atcold commented on docs/ar/week03/03-3.md
> +translation data: 27 Aug 2020
`translation-date` without space and with a dash.

2020-09-30 01:06 UTC, Atcold commented on docs/ar/week03/03-3.md
> +<div dir='rtl'>
Remove.

2020-09-30 01:06 UTC, Atcold commented on docs/ar/week03/03-3.md
> +</div>
Remove.

2020-10-01 04:10 UTC, Atcold requested changes
Please, fix the following issues.
Thanks!

2020-10-01 04:10 UTC, Atcold commented on docs/ar/week03/03-2.md
> +=======
What is this?

2020-10-01 04:10 UTC, Atcold commented on docs/ar/week03/03-3.md
> +<!-----
What is this?

2020-10-01 04:10 UTC, Atcold commented on docs/ar/week03/03-3.md
> +----->
These are supposed to be three dashes `---`.

2020-10-02 15:41 UTC, Atcold approved these changes
Great! Thanks!

2020-10-02 15:42 UTC, merged