05-1
Atcold/pytorch-Deep-Learning pull request #588
Opened 2020-09-19 16:25 UTC by WejdanAlOtaibi

2020-09-20 01:08 UTC, AliEl-01 commented
Hi Wejdan, 
Please edit the name of your PR from **05-1** to** [AR] 05-1.md** or** [AR] Translation of 05-1.md** ... just to know that this is an Arabic one! 
TnQ

2020-09-20 12:22 UTC, AliEl-01 requested changes

2020-09-20 12:22 UTC, AliEl-01 commented on docs/ar/week05/05-1.md
> +<b>Figure 1:</b> مقياس خطوات 1D Quadratic
Hi, 
Please if you can translate the terme ^Figure^ into ^الشكل^. That's will be better.
TnQ

2020-09-20 12:22 UTC, AliEl-01 commented on docs/ar/week05/05-1.md
> +في التحزيم الصغير سنضع بعين الاعتبار الخسارة على العديد من instances المختارة بشكل عشوائي بدلا من حسابها على instance واحد فقط.
Actually I don't know why the term ^instance^ is not translated !!!

2020-09-20 17:09 UTC, WejdanAlOtaibi commented
I modified what’s needed, I uploaded the file to the folder, do I need to
send another pull request??

Le dim. 20 sept. 2020 à 3:22 PM, Ali Elfilali <notifications@github.com> a
écrit :

>
>
> *@AliEl-01* requested changes on this pull request.
>
>
>
>
> ------------------------------
>
>
>
>
> In docs/ar/week05/05-1.md
> <https://github.com/Atcold/pytorch-Deep-Learning/pull/588#discussion_r491685628>
> :
>
>
> > +
>
> +
>
> +مع الوضع في الحسبان أن الدالة $f$ هي دالة مستمرة وقابلة للأشتقاق
>
> +هدفنا هو أن نجد اكثر نقطة منخفضة (الوادي) لدالة التحسين. بغض النظر عن اتجاه هذا الوادي أي أن الاتجاه غير معلوم.
>
> + نحن فقط سنرى ونبحث بشكل محلي ولذلك الأتجاه السلبي التدريجي يعتبر أفضل معلومة لدينا. اتخاذ خطوة صغيرة إلى ذلك الأتجاه سيقربنا للحد الادنى. ما أن نأخذ خطوة صغيرة سنعيد مره اخرى تحديد التدريج الجديد ومره أخرى سنتحرك لذاك الأتجاه بكميات وخطوات صغيرة حتى نصل للوادي.
>
> + وبشكل عام ما يفعله الانحدار التدريجي هو إتباع أتجاه شديد الانحدار (تدريج سلبي)
>
> +
>
> +
>
> +المدخل $\gamma$ في المعادلة التحديثية التكرارية يسمى **مقياس الخطوة**. بشكل عام نحن لا نعرف القيمة المثالية لمقياس الخطوة ولذلك سنضطر تجربة قيم مختلفة.
>
> +المعيار القياسي سيكون تجربة مجموعة من القيم على ميزان للأداء ونختار أفضل قيمة بناء على الميزان. هنالك سناريوهات مختلفة قد تحدثز
>
> +الصورة بالأعلى تصف هذه السناريوهات بالنسبة 1D quadratic.إذا معدل التعلم منخفض للغاية إذن سنضطر لخلق تقدم ثابت للوصول إلى الحد الأدنى.ولكن هذه  الخطوة ستأخذ وقت اطول من الوقت المثالي.
>
> +صعب جدا (وشبه مستحيل ) أن نحصل على مقياس خطوة يصلنا بشكل مباشر للحد الأدنى. ما سنريده بشكل مثالي هو أن نحصل على مقياس خطوة اكبر بقليل من القياس المثالي. هذا ما سعطينا اسرع تقارب (convergence). ولكن إذا استعملنا معدل تعلم كبير التكرار سيصبح أبعد وأبعد من الحد الأدنى وسنحصل على تباعد (divergence). نريد أن نستعمل معدل تعلم قليل البعد (less diverging).
>
> +
>
> +<center>
>
> +<img src="{{site.baseurl}}/images/week05/05-1/step-size.png" style="zoom: 70%; background-color:#DCDCDC;" /><br>
>
> +<b>Figure 1:</b> مقياس خطوات 1D Quadratic
>
>
>
> Hi,
>
>
> Please if you can translate the terme ^Figure^ into ^الشكل^. That's will
> be better.
>
>
> TnQ
>
>
>
>
> ------------------------------
>
>
>
>
> In docs/ar/week05/05-1.md
> <https://github.com/Atcold/pytorch-Deep-Learning/pull/588#discussion_r491686144>
> :
>
>
> > +ومع كونه سريع الـ(SGD) يستطبع ايضا جلب نتائج أفضل من نتائج النزول التدريجي للـfull-batch. الازعاج في الـ(SGD) يستطيع ايضا مساعدتنا لتجنب سطحية القيمة الصغرى المحلية وايجاد قيمة صغرى افضل (واعمق) هذه الظاهرة تسمى **تليين** (Annealing)
>
> +<center>
>
> +<img src="{{site.baseurl}}/images/week05/05-1/annealing.png"/><br>
>
> +<b>Figure 2:</b> التليين مع SGD
>
> +</center>
>
> +
>
> +بشكل مختصر فوائد النزول التدريجي العشوائي هي:
>
> + 1. هنالك الكثير من المعلومات المتكررة في جميع الـinstances. الـ(SGD) يمنع الكثير من تلك العمليات المكررة.
>
> + 2. في المراحل الابتدائية الازعاج يعتبر بكميات قليلة مقارنة بالمعلومات في التدرج. وهكذا خطوة الـ(SGD) جيدة مثل خطوة الـGD ولكن بشكل افتراضي
>
> + 3. *التليين* - الازعاج في تحديث SGD يستطيع أن يمنع التقارب لقيمة صغرى محلية سيئة (سطحية)
>
> + 4. النزول التدريجي العشوائي تكلفة تشغيله تعتبر منخفضة (لأنك لن تتجاوز جميع النقاط البيانات).
>
> +
>
> +
>
> +### (Mini-batching) التحزيم الصغير
>
> +
>
> +في التحزيم الصغير سنضع بعين الاعتبار الخسارة على العديد من instances المختارة بشكل عشوائي بدلا من حسابها على instance واحد فقط.
>
>
>
> Actually I don't know why the term ^instance^ is not translated !!!
>
>
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Atcold/pytorch-Deep-Learning/pull/588#pullrequestreview-492191326>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APJS7GWOTY45YN23VLRAABTSGXXYZANCNFSM4RTDLQFQ>
> .
>
>
>

2020-09-20 17:17 UTC, WejdanAlOtaibi commented
05-1 [AR]

2020-09-20 17:24 UTC, AliEl-01 commented
Great! As I see now it's Good!

2020-09-23 02:45 UTC, Atcold requested changes
Please, edit `docs/_config.yml` as well.

2020-09-23 02:45 UTC, Atcold commented on docs/ar/week05/05-1.md
> +lang-ref: ch.05-1
`lang: ar` missing.

2020-09-23 02:45 UTC, Atcold commented on docs/ar/week05/05-1.md
> +Translator: Wejdan AlOtaibi
Lowercase T, so `translator:`.
`translation-date:` missing as well.

2020-09-23 02:52 UTC, Atcold approved these changes
Fixed these myself.

2020-09-23 02:53 UTC, merged