[AR] Translation of 14-2.md
Atcold/pytorch-Deep-Learning pull request #591
Opened 2020-09-19 23:27 UTC by anasselhoud

2020-09-20 01:17 UTC, AliEl-01 reviewed
Hi Anas
I think the translation will be better If the title is translated 😅 
TnQ

2020-09-20 11:27 UTC, anasselhoud commented
> Hi Anas
> I think the translation will be better If the title is translated 😅
> TnQ

@AliEl-01 Yeah, forgot that. Thanks for the notice.

2020-09-23 02:39 UTC, Atcold requested changes
You need to update `docs/_config.yml` as well.

2020-09-23 02:39 UTC, Atcold commented on docs/ar/week14/14-2.md
> +date: 15 Sep 2020
```suggestion
translation-date: 15 Sep 2020
```

2020-09-23 08:53 UTC, anasselhoud commented
@Atcold Done. Ready to be merged, I suppose.

2020-09-23 13:40 UTC, AliEl-01 reviewed
THE TITLE could be translated in a better way! I see that
 " أساليب الرسم البياني القائم على الطاقة " 
OR
 " أساليب الرسومية القائمة على الطاقة " 
It will be better as translation!

2020-09-23 17:06 UTC, Atcold approved these changes
Great, merging now.
We can update title and other stuff during the review process.

2020-09-24 07:54 UTC, anasselhoud commented
> THE TITLE could be translated in a better way! I see that
> " أساليب الرسم البياني القائم على الطاقة "
> OR
> " أساليب الرسومية القائمة على الطاقة "
> It will be better as translation!

@AliEl-01  The second proposition is 'google translate' generated, not accurate at all. There is nothing called أساليب الرسومية in Arabic. I can go with the first one even if I am not convinced.
As I always say, this is a technical article. You should translate it into a technical article. So knowing the context is important to make the translation understanble technically not just languistically. 
I believe we should leave the reviewing part to someone who has more knowledge in both Deep Learning and Arabic (I study DL and it's my last year studying and even though I don't feel competent to review a whole work), you can eventually discuss it all together in Slack group.

2020-09-24 07:56 UTC, closed without merging