10-2.md spanish translation
Atcold/pytorch-Deep-Learning pull request #597
Opened 2020-09-20 15:04 UTC by tiagogiraldo

Attached is the Spanish translation of the 10-2.md.  It is ready for review.

2020-09-20 15:24 UTC, xcastilla commented on docs/es/week10/10-2.md
> +Sin embargo, no está muy claro por qué la realización de una tarea no semántica debe producir buenas características... Por ejemplo, ¿por qué deberíamos esperar aprender sobre "semántica" mientras re
```suggestion
Sin embargo, no está muy claro por qué la realización de una tarea no semántica debe producir buenas características... Por ejemplo, ¿por qué deberíamos esperar aprender sobre "semántica" mientras resolvemos algo como un rompecabezas? ¿O por qué se espera que "predecir hashtags" a partir de imágenes ayude a aprender un clasificador en tareas de transferencia? Por lo tanto, la pregunta sigue siendo: ¿Cómo deberíamos diseñar buenas tareas de pre-entrenamiento que estén bien alineadas con las tareas de transferencia?
```

2020-09-20 15:28 UTC, xcastilla commented on docs/es/week10/10-2.md
> +Dos formas de lograr las propiedades anteriores son **Agrupamiento** y **Aprendizaje Constrastivo**. Que han comenzado a desempeñarse mucho mejor que las tareas de pretexto que se diseñaron hasta aho
```suggestion
Dos formas de lograr las propiedades anteriores son **Agrupamiento** y **Aprendizaje Constrastivo**, que han comenzado a desempeñarse mucho mejor que las tareas de pretexto que se diseñaron hasta ahora. Un método que pertenece a la agrupación en clústeres es **ClusterFit** y otro que cae en invariancia es **ARIP**.
```
o bien esta otra:

```suggestion
Dos formas de lograr las propiedades anteriores son **Agrupamiento** y **Aprendizaje Constrastivo**. Estos métodos han comenzado a desempeñarse mucho mejor que las tareas de pretexto que se diseñaron hasta ahora. Un método que pertenece a la agrupación en clústeres es **ClusterFit** y otro que cae en invariancia es **ARIP**.
```

2020-09-20 15:45 UTC, xcastilla commented on docs/es/week10/10-2.md
> +Ahora pasamos a PIRL un poco, y eso es tratar de entender cuál es la principal diferencia de las tareas de pretexto y cómo el aprendizaje contrastivo es muy diferente de las tareas de pretexto. De nu
```suggestion
Ahora pasamos a ARPI un poco, y eso es tratar de entender cuál es la principal diferencia de las tareas de pretexto y cómo el aprendizaje contrastivo es muy diferente de las tareas de pretexto. De nuevo, las tareas con pretexto siempre razonan sobre una sola imagen a la vez. Así que la idea es que dándole a una imagen su y previa transformación a esa imagen, en este caso una transformación de rompecabezas, y luego introduciendo esta imagen transformada en una ConvNet e intentando predecir la propiedad de la transformación que aplicaste, la permutación que aplicaste o la rotación que aplicaste o el tipo de color que removiste y así sucesivamente. Así que las tareas de pretexto siempre razonan sobre una sola imagen. Y la segunda cosa es que la tarea que estás realizando en este caso realmente tiene que capturar alguna propiedad de la transformación. Así que realmente tiene que capturar la permutación exacta que se aplican o el tipo de rotación que se aplican, lo que significa que las representaciones de la última capa van a ir mucho ARPI como la transformación de los cambios y eso es por diseño, porque realmente estás tratando de resolver las tareas de pretexto. Pero desafortunadamente, lo que esto significa es que las representaciones de la última capa capturan una propiedad de muy bajo nivel de la señal. Estas capturan cosas como la rotación o algo así. Mientras que lo que se diseña o lo que se espera de estas representaciones es que sean invarintes a estas cosas que debería ser capaz de reconocer un gato, no importa si el gato está en posición vertical o que el gato esté, digamos, inclinado como 90 grados. Mientras que cuando estás resolviendo esa tarea de pretexto particular se impone exactamente lo contrario. Estamos diciendo que deberíamos ser capaces de reconocer si esta imagen está en posición vertical o si esta imagen está básicamente girada hacia los lados. Hay muchas excepciones en las que realmente quieres que estas representaciones de bajo nivel sean covariantes y muchas de ellas tienen que ver con las tareas que estás realizando y bastantes tareas en 3D realmente quieren ser predictivas. Así que quieres predecir qué transformaciones de cámara tienes: estás viendo dos vistas del mismo objeto o algo así. Pero a menos que tengas ese tipo de aplicación específica para muchas tareas semánticas, realmente quieres ser invariante a las transformaciones que se utilizan para usar esa entrada.
```

2020-09-20 15:56 UTC, xcastilla commented on docs/es/week10/10-2.md
> +Ahora, volviendo a la verificación de los características semánticas, miramos la precisión Top-1 para el ARPI y el rompecabezas para diferentes capas de representación desde "conv1" a "res5". Es inte
```suggestion
Ahora, volviendo a la verificación de los características semánticas, miramos la precisión Top-1 para el ARPI y el rompecabezas para diferentes capas de representación desde "conv1" a "res5". Es interesante observar que la precisión sigue aumentando para las diferentes capas tanto para el ARPI como para el rompecabezas, pero disminuye en la 5ª capa para el rompecabezas. Mientras que, la precisión sigue mejorando para ARPI, *i.e.*, más y más semántica.
```

2020-09-20 15:58 UTC, xcastilla commented on docs/es/week10/10-2.md
> +PIRL is very good at handling problem complexity because you're never predicting the number of permutations, you're just using them as input. So, PIRL can easily scale to all 362,880 possible permuta
It seems you skipped the translation of this part 😄

2020-09-20 15:59 UTC, xcastilla commented on docs/es/week10/10-2.md
> +3. ¿Qué invariancias importa? (Uno podría pensar en qué invariancias funcionan para una tarea supervisada en general como trabajo futuro).
```suggestion
3. ¿Qué invariancias importan? (Uno podría pensar en qué invariancias funcionan para una tarea supervisada en general como trabajo futuro).
```

2020-09-20 16:00 UTC, xcastilla commented on docs/es/week10/10-2.md
> +**Resp**: *En e ARPI, no se observó tal fenómeno, así que sólo se utilizó la norma habitual de lotes*
```suggestion
**Resp**: *En ARPI, no se observó tal fenómeno, así que sólo se utilizó la norma habitual de lotes*
```

2020-09-20 16:02 UTC, xcastilla commented on docs/es/week10/10-2.md
> +3. ¿Funciona la norma de lote en el papel en el ARPI sólo porque se implementa como un banco de memoria - ya que todas las representaciones no se toman al mismo tiempo? (Como las normas de lote no se
```suggestion
3. ¿Funciona la norma de lote en el papel en el ARPI sólo porque se implementa como un banco de memoria - ya que todas las representaciones no se toman al mismo tiempo? (Como las normas de lote no se utilizan específicamente en el artículo de MoCo, por ejemplo)
```

2020-09-20 16:02 UTC, xcastilla commented on docs/es/week10/10-2.md
> +**Resp**: *Sí. En el PIRL, el mismo lote no tiene todas las representaciones y posiblemente por qué la norma del lote funciona aquí, lo que podría no ser el caso para otras tareas donde las represent
```suggestion
**Resp**: *Sí. En el ARPI, el mismo lote no tiene todas las representaciones y posiblemente por qué la norma del lote funciona aquí, lo que podría no ser el caso para otras tareas donde las representaciones están todas correlacionadas dentro del lote*
```

2020-09-20 16:09 UTC, xcastilla commented
You will need to add the path to this lesson (10-2) in [this file](https://github.com/Atcold/pytorch-Deep-Learning/blob/b8c8188d9d3774b84368f31c53412a0713435013/docs/_config.yml) as well

2020-09-20 16:11 UTC, xcastilla requested changes
I left some comments. Some of the suggestions are very trivial but I thought might improve readability. Nice translation anyway, it was really easy to read 👍

2020-09-20 17:25 UTC, tiagogiraldo reviewed
The changes are ready, except for the missing translation fragment that I upload in a moment.

2020-09-21 02:25 UTC, JonathanSum commented
Don't forget to put [ES] at the starting of the title.

2020-09-21 06:29 UTC, xcastilla approved these changes
Looks good!

2020-09-23 03:09 UTC, Atcold requested changes
You need to update `docs/_config.yml` as well.

2020-09-23 03:09 UTC, Atcold commented on docs/es/week10/10-2.md
> +title: Self-Supervised Learning - ClusterFit and PIRL
Title needs translation.

2020-09-23 03:09 UTC, Atcold commented on docs/es/week10/10-2.md
> +translation-date:
Missing date.

2020-09-23 03:34 UTC, tiagogiraldo commented on docs/es/week10/10-2.md
> +translation-date:
I've already made the change

2020-09-23 03:39 UTC, tiagogiraldo commented on docs/es/week10/10-2.md
> +title: Self-Supervised Learning - ClusterFit and PIRL
I've already made the change

2020-09-23 04:17 UTC, Atcold approved these changes
Thanks! I've updated `docs/_config.yml` for you.

2020-09-23 04:18 UTC, merged