Translation of 13-1.md
Atcold/pytorch-Deep-Learning pull request #600
Opened 2020-09-20 21:13 UTC by arahiche

2020-09-21 02:23 UTC, JonathanSum commented
Don't forget to put it in [AR ] Translation of 13-1.md

2020-09-21 16:46 UTC, AliEl-01 requested changes

2020-09-21 16:46 UTC, AliEl-01 commented on docs/ar/week13/13-1.md
> +### الخطوة الثانية: وظائف فوريي
i think term "fuctions" should be translated into "دوال"

2020-09-21 16:46 UTC, AliEl-01 commented on docs/ar/week13/13-1.md
> +ما يلي هو التحليل الذاتي لمخطط لابلاسيان ،
النسبة تكون عبر ياء النسبة لتعطينا كلملة "مخطط لابلاسي" عوض مخطط لابلاسيان

and i think this is for every "Laplacian" term in the text!

2020-09-21 17:32 UTC, arahiche commented on docs/ar/week13/13-1.md
> +ما يلي هو التحليل الذاتي لمخطط لابلاسيان ،
Laplacian denotes Laplace operator, a word that I preferred to write it as it in Arabic letters without translation, and I think لابلاسيان is more sounding than لابلاسي. However, ff you have a reference for لابلاسي so please let me know.

2020-09-21 17:34 UTC, arahiche commented on docs/ar/week13/13-1.md
> +### الخطوة الثانية: وظائف فوريي
you're right

2020-09-21 18:09 UTC, AliEl-01 commented on docs/ar/week13/13-1.md
> +ما يلي هو التحليل الذاتي لمخطط لابلاسيان ،
I think you already know that in arabic we have something we call it "النسبة" so the rule say that we add "ي" to the original term, in our case our original term is laplace=لابلاس so laplacian=لابلاسي.
I don't know if I make it clear or not but I think you already know that 😄

2020-09-23 03:44 UTC, Atcold approved these changes
I've updated `docs/_config.yml` for you.

2020-09-23 03:45 UTC, merged