[KR] 14-3.md
Atcold/pytorch-Deep-Learning pull request #614
Opened 2020-09-23 07:25 UTC by marofmar

Korean translation of 14-3.md

2020-09-23 16:45 UTC, Atcold requested changes
Great! Please, update `docs/_config.yml`.

@skyil7, please review.

2020-09-23 16:53 UTC, marofmar commented
Just updated docs/_config.yml ! Thanks!

2020-09-27 04:01 UTC, skyil7 requested changes
리뷰 완료했습니다! 반영 부탁드립니다.

2020-09-27 09:34 UTC, marofmar commented
@skyil7 리뷰 반영하여 수정했습니다, 좋은 포인트 감사드립니다!

2020-09-29 04:40 UTC, skyil7 approved these changes
수고하셨습니다! 즐거운 연휴 되세요~

2020-09-29 04:40 UTC, merged

2020-09-30 01:35 UTC, Atcold commented
Thank you both!