[RU] translations of 01-1.md 01.md index.md and README-RU.md
Atcold/pytorch-Deep-Learning pull request #624
Opened 2020-09-25 15:24 UTC by MrPark97

full translations of 01-1.md 01.md index.md and README-RU.md. Config also changed. Wiki up-to-date

2020-09-25 16:37 UTC, vladisai requested changes

2020-09-25 16:37 UTC, vladisai commented on docs/ru/week-1/01-1.md
> +Глубокое обучение вновь стало популярным в 1985 году, с появлением метода обратного распространения ошибки. В 1995 году исследования в этой области снова прекратились, и сообщество машинного обучения
наблдался => наблюдался

2020-09-25 16:37 UTC, vladisai commented on docs/ru/week-1/01-1.md
> +$90\%$ приложений глубокого обучения используют обучение с учителем. Обучение с учителем это процесс, в котором в котором вы собираете кучу пар входных и выходных данных, эти входные данные скармлива
"эти входные данные скармливаются нейронной сети, чтобы обучиться на корректных выходных данных."
Я бы сказал:
"нейросеть получает входные данные и учится предсказывать правильные выходные данные.

2020-09-25 16:37 UTC, vladisai commented on docs/ru/week-1/01-1.md
> +Обучение с учителем просиходит от Перцептрона и Adaline. Adaline основывается на той же архитектуре со взвешенными входами; когда значение выше порога, он активирован, когда ниже, он деактивирован. П
вместо ; должно быть :

2020-09-25 16:37 UTC, vladisai commented on docs/ru/week-1/01-1.md
> +После появления и развития глубокого обучения, 2-хэтапный процесс сменился последовательностью модулей. В каждом модуле есть настраиваемые параметры и нелинейность. Так можно соединять их, создавая м
кторой -> которой

2020-09-25 16:37 UTC, vladisai commented on docs/ru/week-1/01-1.md
> +Простейшая многослойная архитектура с настраиваемыми параметрами может быть следующей: вход представлен вектором таким, как изображение или аудио. Этот вход умножается на матрицу весов, коэффициенты
Причина, по которой эта архитектура называется нейронной сетью, она вычисляет взвешенную сумму входов по соответствующим строкам матрицы.

я бы написал так

Эта архитектура называется нейронной сетью, потому что она вычисляет взвешенную сумму входов по соответствующим строкам матрицы.

2020-09-25 16:37 UTC, vladisai commented on docs/ru/README-RU.md
> +Чтобы видеть контент соответсвующим образом в классическом интерфейсе, установите следующее:
соответствующим

2020-09-25 17:22 UTC, MrPark97 commented on docs/ru/README-RU.md
> +Чтобы видеть контент соответсвующим образом в классическом интерфейсе, установите следующее:
Исправил все замечания, проверьте, пожалуйста. Спасибо за отзыв!

2020-09-25 17:55 UTC, katesolonko approved these changes

2020-09-26 03:58 UTC, Atcold requested changes
Impressive! Спасибо!

2020-09-26 03:58 UTC, Atcold commented on docs/ru/README-RU.md
> +-->
```suggestion

```

2020-09-26 03:58 UTC, Atcold commented on docs/ru/README-RU.md
> +[🇬🇧](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/README.md) &nbsp; [🇨🇳](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/zh/README-ZH.md) &nbsp; [🇰🇷](https://github.co
Add French 🇫🇷, Persian 🇮🇷, Russian 🇷🇺.

2020-09-26 03:58 UTC, Atcold commented on docs/ru/README-RU.md
> +У данного репозитория с рабочими тетрадями сейчас есть [сопровождающий сайт](https://atcold.github.io/pytorch-Deep-Learning/), где Вы можете все материалы в текстовом и видео-формате.
```suggestion
У данного репозитория с рабочими тетрадями сейчас есть [сопровождающий сайт](https://atcold.github.io/pytorch-Deep-Learning/ru/), где Вы можете все материалы в текстовом и видео-формате.
```

2020-09-26 03:58 UTC, Atcold commented on docs/ru/README-RU.md
> +[🇬🇧](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/README.md) &nbsp; [🇨🇳](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/zh/README-ZH.md) &nbsp; [🇰🇷](https://github.co
Update *all* other `README-XX.md` with the Russian language.

2020-09-26 03:58 UTC, Atcold commented on docs/ru/index.md
> +title: DEEP LEARNING
Translate "DEEP LEARNING" to Russian, all caps.

2020-09-26 03:58 UTC, Atcold commented on docs/ru/index.md
> +        <a href="https://github.com/Atcold/pytorch-Deep-Learning/blob/master/08-seq_classification.ipynb">📓</a>
I've added one more link here, check the latest version.

2020-09-26 03:58 UTC, Atcold commented on docs/ru/index.md
> +
Week 14 is now available.

2020-09-26 06:35 UTC, MrPark97 commented on docs/ru/index.md
> +
All fixed. Check, please!

2020-09-30 00:56 UTC, Atcold approved these changes
Great! Thanks so much!

2020-09-30 00:56 UTC, merged