[FA] Translation of 13, 13-1
Atcold/pytorch-Deep-Learning pull request #626
Opened 2020-09-26 09:17 UTC by ZhabizGIT

2020-09-28 13:37 UTC, telegraphroad requested changes
Overall well translated, thanks! There are some minor issues in the translations of specific terms, also some nuances in the translation of sentences. I'd suggest a revision of the text to make sure it's easy to read. Also ask in the group for suggestions on specific terms if you're not sure.

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +شبکه های عصبی کانولوشنی سنتی از معماری قدرتمند برای حل مسایل یادگیری ماشینی با دامنه ورودی با ابعاد بالا برخوردار هستند.
دامنه ی ورودی یا ابعاد؟

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +### نفرین بعدیت چیست؟
بعدیت؟ نفرین ابعاد بهتر نیست؟

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +یک عکس با ابعاد 1024 در 1024 پیکسلی را در نظر بگیرید. این عکس را می توان نقطه ای در فضا در نظر گرفت که با یک میلیون بعد توصیف می شود. استفاده از 10 نمونه از این عکس ها از نظر بعد اندازه ای برابر با $
شدیدا عددی بزرگ >> عددی بسیار بزرگی است.
فکر می کنم بد نباشه متن یه بار بازخوانی بشه از نظر روان بودن

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +- برای **N = 10** نمونه/دامنه --> **${10}^{1,000,000}$ نقطه**
دامنه یا ابعاد؟

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +<b>شکل 1:</b>شبکه های CovNets نمایشی از داده های تصویری با ابعاد بالا را استخراج می کنند.
ریپریزنتیشن نمایش ترجمه شده؟ بازنمایی بهتر نیست؟ اگر مطمین نیستید توی گروه مطرح کنید لطفن

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> + **1. داده (تصاویر، ویدیو، گفتار صوتی) دارای ساختار مرکب هستند**
مرکب یا ترکیبی؟ با بقیه ترجمه ها چک بشه که یکنواخت ترجمه شده باشه

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +داده ها از مجموعه ای از الگوها تشکیل شده اند:
شده اند از جمله الگوهای:

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +* **محلی**  یک نرون در شبکه عصبی بجای اتصال به تمامی لایه ها در شبکه تنها به لایه های همسایه متصل است
جمله‌ی دوم ترجمه نشده

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +* **سلسله مراتبی** ترکیب ویژگیهای مرتبه پایین ویژگی های مرتبه متو سط را تشکیل می  دهند. سپس ترکیب این ویژگیهای مرتبه متوسط به صورت ادامه دار ویژگیهای مرتبه های بالاتر را تشکیل می دهد.مثال نمایش تصویر
نمایش تصویرگرا؟ یا بازنمایی تصویری؟

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +**2. شبکه های عصبی کانولوشنی از ساختار ترکیب بندی سود می برند.**
ترکیب بندی؟

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +</center>
رجوع به کامنت قبلی

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +* جملات، کلمات، گفتار در یک فضای یک بعدی قرار می گیرند. به عنوان مثال هر حرف می تواند با یک عدد نمایش داده شود.
اقلیدسی یک بعدی. با یک عدد صحیح

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +* این دامنه ها دارای ساختار منظم فضایی هستند که شرایط را برای اجرای عملیات  توسط شبکه های عصبی کانولوشنی به صورت سریع و با فرمولاسیون ریاضی به خوبی تعریف شده، فراهم می آورند.
به خوبی تعریف شده>>خوش تعریف

2020-09-28 13:37 UTC, telegraphroad commented on docs/fa/week13/13-1.md
> +یک شبکه اجتماعی را در نظر بگیرید. یک شبکه اجتماعی با یک نمایش گرافی به طرز عالی توصیف می شود چون پیوند های دو به دو بین کاربران در شبکه ساختار مشبک ندارند. گره ها در گراف نمایش دهنده کاربران در شبکه
ساختار مشبک ندارند؟ یا تشکیل یه شبکه نمی دهند. ممکنه گمراه کننده باشه کمی
یال ها بین گره ها اتصال بین گره ها >> یال های بین دو گره اتصال بین آن دو گره(کاربر) را نمایش می‌دهند
ماتریس سه بعدی
که شامل پیغام ها >> که شامل مواردی مانند پیام ها، تصاویر و ویدیوها است. جمله ی اصلی و ترجمه ی من القا می کنند که ماتریس محدود به این سه مورد نیست

2020-09-30 01:24 UTC, Atcold approved these changes
Great, thanks!

2020-09-30 01:25 UTC, merged

2020-09-30 01:26 UTC, Atcold commented
Oops, I just noticed @telegraphroad asked for some edits.
@ZhabizGIT, can you please send these edits via a new PR?

Thank you both!