[AR] Translation of 14-2.md
Atcold/pytorch-Deep-Learning pull request #627
Opened 2020-09-26 09:44 UTC by anasselhoud

There was an error with merging the last PR. So I closed it and created a new one.

2020-09-28 18:52 UTC, hayaalsh commented
Great job Anass! Honestly there is nothing much to change. Only few comments on the terms.

- Could you please add your translation of the following to the terms table: Sliding window, sigmoid, hinge, forward algorithm, belief-propagation algorithm, log sum exponential, negative log-likelihood, negative log-likelihood loss, log sum exponential, Lagrangian, entropy.
- Terms that do not translate, e.g., softmax, Viterbi, can be add to the table. But set their translation to their same English name (see term "Adaline").
- Line 93:  remove ة to get "أكبر من بعض القيم" instead of "أكبر من بعض القيمة"
- Line 171: add your translation of "Negative Log-Likelihood" along with the English name in brackets as your did in line 264.
- Line 410: "خاصية لمجموعة التوزيع" instead of "خاصية لعائلة التوزيع" 
- Line 412: "معاملات النموذج" instead of "معلمات النموذج"
- Line 416: "حساب سجل مجموع الأسي log of a sum of exponentials" add brackets, or remove the English term. You can add the English term on line 200 where the term was first mentioned in your text.

2020-09-28 21:04 UTC, hayaalsh requested changes
Great job Anass! Honestly there is nothing much to change. Only few comments on the terms and some missing captions.

- Could you also add your translation of the following to the terms table: sliding window, sigmoid, hinge, forward algorithm, belief-propagation algorithm, log sum exponential, negative log-likelihood, negative log-likelihood loss, Lagrangian, entropy.
- Terms that do not translate, e.g., softmax, Viterbi, can be add to the table. But set their translation to their same English name (see term "Adaline").

2020-09-28 21:04 UTC, hayaalsh commented on docs/ar/week14/14-2.md
> +الشكل 1:
Add Arabic translation of Figure 1 caption.

2020-09-28 21:04 UTC, hayaalsh commented on docs/ar/week14/14-2.md
> +<b>الشكل 6:</b> Jensen's Inequality (taken from [Wikipedia](https://en.wikipedia.org/wiki/Jensen%27s_inequality))
Translate Figure 6 caption.

2020-09-29 19:59 UTC, anasselhoud commented
@hayaalsh  That's not how we work here with Github. Reviewing is a step apart. When @Atcold merge the PR, you can send a new pull request with all the changes.

2020-09-29 20:01 UTC, anasselhoud commented
Thank you @hayaalsh for your comments. Please wait until @Atcold merge the PR, you can send a new pull request with all the changes so it counts as your proper contribution too (if I changed now, it will be counted as my contribution alone.

2020-09-30 01:43 UTC, Atcold approved these changes
Great! Please send a new PR with the revised content.

2020-09-30 01:44 UTC, merged