[FA] Translation of Readme files of the fourth week
Atcold/pytorch-Deep-Learning pull request #631
Opened 2020-09-27 13:05 UTC by erfanMhi

2020-09-30 01:04 UTC, Atcold requested changes
Great! Just translate the titles, and we're good here!

2020-09-30 01:04 UTC, Atcold commented on docs/fa/week04/04-1.md
> +title: Linear Algebra and Convolutions
The title needs translation.

2020-09-30 01:04 UTC, Atcold commented on docs/fa/week04/04.md
> +title: Week 4
The title needs translation.

2020-09-30 09:17 UTC, erfanMhi commented
Dear Dr. Canziani,

The titles of the aforementioned Readmes have been translated to Farsi/Persian, and they are now ready to be published.

2020-09-30 09:25 UTC, erfanMhi commented
Just to point out that the title of '03-3.md' Readme file hasn't been translated into Farsi too.  I wonder whether it would be ok to translate the title of this file which actually belong to week03 and update my pull request?

2020-10-01 04:07 UTC, Atcold approved these changes

2020-10-01 04:07 UTC, merged