[FR] Few markdown corrections
Atcold/pytorch-Deep-Learning pull request #642
Opened 2020-09-30 07:37 UTC by lbourdois

I was optimistic that my previous PR would be the last. Again some corrections.

While checking the rendering on the site, I realized that for the 13-1 file, two English flag files were proposed.
I proposed a correction to fix that.

2020-10-01 04:05 UTC, Atcold requested changes
Small edit.

2020-10-01 04:05 UTC, Atcold commented on docs/fr/index.md
> +|Instructeur|<img src="images/Yann.png" width="100" height="100">|<a href="https://twitter.com/ylecun">Yann Le Cun</a><br>yann@cs.nyu.edu|Silver Professor en Computer Science à l'Université de New Yo
```suggestion
|Instructeur|<img src="images/Yann.png" width="100" height="100">|<a href="https://twitter.com/ylecun">Yann Le Cun</a><br>yann@cs.nyu.edu|Silver Professor en Computer Science à la New York University (NYU) <br> et lauréat du prix Turing 2019|
```

2020-10-01 06:49 UTC, lbourdois commented
Done.

2020-10-02 15:39 UTC, Atcold approved these changes
Great, thanks!

2020-10-02 15:39 UTC, merged