Editing practicum 08
Atcold/pytorch-Deep-Learning pull request #645
Opened 2020-10-01 20:30 UTC by jemappelleMarie

You're super cute, and it's so distracting for those who're watching the video of your class ;)
I even think the subtitle auto-generator was distracted as the subtitle was full of mistakes!

2020-10-02 06:52 UTC, telegraphroad requested changes
Herculean effort, awesome job! Thanks a lot Maryam. I understand how time consuming and tedious it must be to do the captions, especially with the community tools gone.

I went through 5 minutes of practicum 8. I've left some comments. All small stuff and very infrequent, but nevertheless things that could be misleading to people without proper background. It felt like nitpicking but I tried my best not to, only marked the parts that would change the meaning of the sentence. 

Would it be too much to ask a quick review of the transcript, maybe in 2x speed? I did it for mine, just let Yann talk super fast and followed the captions on my file to make sure I haven't missed anything.

I haven't checked the other two captions, might be 100% clean. But anyway it would be wonderful if you could just double-check the first few minutes to see if you've missed anything.

2020-10-02 06:52 UTC, telegraphroad commented on docs/en/week08/practicum08.sbv
> +which gives us a code so h which was
0:01:13.920,0:01:17.900
this network out to layer neural net>>...a two layer...

2020-10-02 06:52 UTC, telegraphroad commented on docs/en/week08/practicum08.sbv
>  you're gonna be seen what is a variation
variational

2020-10-02 06:52 UTC, telegraphroad commented on docs/en/week08/practicum08.sbv
> +a variation auto-encoder okay it looks
variational

2020-10-02 06:52 UTC, telegraphroad commented on docs/en/week08/practicum08.sbv
> +of capital E of z and V of z and they're
0:03:02.200,0:03:08.439
having the hidden layer age now we have>>hidden layer h

2020-10-02 06:52 UTC, telegraphroad commented on docs/en/week08/practicum08.sbv
>  0:03:30.669,0:03:36.790
0:03:21.189,0:03:27.969
said then we are going to be sampling   >>  said->z

2020-10-02 06:52 UTC, telegraphroad commented on docs/en/week08/practicum08.sbv
> +to z instead it's my latent variable
z, and z is my latent variable

no "instead" there, might be misleading

2020-10-02 06:52 UTC, telegraphroad commented on docs/en/week08/practicum08.sbv
> +again a deterministic out encoder so h
out encoder>auto-encoder

2020-10-02 17:40 UTC, Atcold requested changes
Thanks! Can you please fix what @telegraphroad has pointed out?

2020-10-04 18:29 UTC, jemappelleMarie commented
Done :)

2020-10-06 04:47 UTC, telegraphroad reviewed
Did some spot checks, everything seems to be in order. 
Thanks!

2020-10-07 05:46 UTC, Atcold approved these changes
Awesome!

2020-10-07 05:47 UTC, merged