[SR] Translation of README
Atcold/pytorch-Deep-Learning pull request #672
Opened 2020-10-17 23:02 UTC by EmaPajic

2020-10-20 13:51 UTC, jecaJeca commented on docs/rs/README-RS.md
> +Ovaj repozitorijum ima [prateći sajt](https://atcold.github.io/pytorch-Deep-Learning/), gde se svi materijali kursa mogu naći u video i tekstualnom formatu.
Mislim da ne treba zarez. Može da se kaže i - gde se svi materijali kursa mogu naći u originalnom video i tekstualnom formatu
Čisto da bude jasno da je engleska verzija a ne srpska.

2020-10-20 13:54 UTC, jecaJeca commented on docs/rs/README-RS.md
> +## Instalacija
Može i _Podešavanje radnog okruženja_

2020-10-20 13:55 UTC, jecaJeca commented on docs/rs/README-RS.md
> +Startovati iz terminala kao uobičajeno:
Možda bez ovoga?

2020-10-20 13:58 UTC, jecaJeca commented on docs/rs/README-RS.md
> +*Jupyter Notebooks* se koriste kroz lekcije za interaktivnu eksploraciju i vizualizaciju.
interaktivno ispitivanje (analizu) podataka i vizuelizaciju

2020-10-20 14:00 UTC, jecaJeca commented on docs/rs/README-RS.md
> +JupyterLab ima ugrađenu tamnu temu koju je moguće odabrati, pa je potrebno instalirati nešto samo ukoliko želite da koristite klasičan interfejs notebook-a.
pa je potrebno izvršiti dodatne instalacija samo ukoliko ...

2020-10-20 14:04 UTC, jecaJeca commented on docs/rs/index.md
> +Ovaj kurs prati najskorije tehnike u dubokom učenju i učenju reprezentacije. Fokusira se na nadgledano i nenadgledano učenje, embedding metode, učenje metrika, konvolucione i rekurentne neuronske mre
je li ovo ispravan prevod graduate-level-a

2020-10-22 21:40 UTC, EmaPajic commented on docs/rs/README-RS.md
> +Ovaj repozitorijum ima [prateći sajt](https://atcold.github.io/pytorch-Deep-Learning/), gde se svi materijali kursa mogu naći u video i tekstualnom formatu.
Tehnički, koliko ja shvatam, na sajtu će moći da se vidi i verzija na srpskom. Ako pogledaš sajt, može da se promeni jezik.

2020-10-22 21:41 UTC, EmaPajic commented on docs/rs/README-RS.md
> +## Instalacija
resolved

2020-10-22 21:41 UTC, EmaPajic commented on docs/rs/README-RS.md
> +Startovati iz terminala kao uobičajeno:
resolved

2020-10-22 21:42 UTC, EmaPajic commented on docs/rs/README-RS.md
> +*Jupyter Notebooks* se koriste kroz lekcije za interaktivnu eksploraciju i vizualizaciju.
resolved

2020-10-22 21:43 UTC, EmaPajic commented on docs/rs/README-RS.md
> +JupyterLab ima ugrađenu tamnu temu koju je moguće odabrati, pa je potrebno instalirati nešto samo ukoliko želite da koristite klasičan interfejs notebook-a.
resolved

2020-10-22 21:45 UTC, EmaPajic commented on docs/rs/index.md
> +Ovaj kurs prati najskorije tehnike u dubokom učenju i učenju reprezentacije. Fokusira se na nadgledano i nenadgledano učenje, embedding metode, učenje metrika, konvolucione i rekurentne neuronske mre
Nisam sigurna kako bi se najpravilnije prevelo, ali van Srbije obično se vodi undergraduate i graduate level pa pretpostavljam da je ok da se kaže ovako

2020-11-12 03:33 UTC, Atcold requested changes
Very good! Let's use `sr` for Serbian (see [our website template](https://github.com/ebetica/jekyllbook/blob/bdfa5ba3ac15eb9e9f74cc17178cc5b686c6c6ba/static/book.js#L313)).
Moreover, you need to update `docs/_config.yml`.
Kindly rename `README-RS.md` into `README-SR.md`.

2020-11-14 12:18 UTC, EmaPajic commented
> Very good! Let's use `sr` for Serbian (see [our website template](https://github.com/ebetica/jekyllbook/blob/bdfa5ba3ac15eb9e9f74cc17178cc5b686c6c6ba/static/book.js#L313)).
> Moreover, you need to update `docs/_config.yml`.
> Kindly rename `README-RS.md` into `README-SR.md`.

Hi, sure, I'll change it. Actually, I wrote sr initially but noticed that that flag for sr is wrong and that Serbian flag is created with rs.

2020-11-25 02:46 UTC, Atcold commented
Hi @EmaPajic. I'm a little confused about your "I'll change it".
`docs/_config.yml` and all the other `README.md`s have not yet been updated.
Am I missing something?

2020-11-26 12:15 UTC, EmaPajic commented
> Hi @EmaPajic. I'm a little confused about your "I'll change it".
> `docs/_config.yml` and all the other `README.md`s have not yet been updated.
> Am I missing something?

Updated now

2020-12-11 02:47 UTC, Atcold approved these changes
Thanks, merging. I'll update the `README.md` for all other languages myself…

2020-12-11 02:52 UTC, merged