[FA] 12-2.md Translation
Atcold/pytorch-Deep-Learning pull request #673
Opened 2020-10-18 05:48 UTC by thisistayeb

2020-10-21 06:21 UTC, telegraphroad commented on docs/fa/week12/12-1.md
> +یک مزیت بزرگ در مورد توجه چند سر این است که به صورت موازی بسیار قابل محاسبه است. برخلاف RNNها، که سرهای ماژول های توجه چند سر و همه مراحل گام را به طور همزمان محاسبه می کند. یک مشکل محاسبه همزمان همه
I'd suggest something a bit more fluent like
یک مزیت بزرگ در مورد توجه چندسر این است که محاسبات آن را به راحتی می‌توان به صورت موازی انجام داد.
I'm not sure about translating time-steps into گام. maybe گام‌های زمانی? sounds awful but conveys the sense that the steps are through time, not on some other axis
I'm not sure about translating mask to پوشش, might be confused with "covering". Does it conform throughout the translations for other parts of the course? If not leaving the "mask" as is might be a good idea.

2020-10-21 06:27 UTC, telegraphroad requested changes
Very nice translation, high quality, Farsi is fluent and pleasant to read. Thanks!

I did some spot checks and found some teeny tiny things that might need your attention. I left comments on one of the paragraphs to give you an idea about what I'm talking about.

My gentle suggestion would be to do a quick review of the translation, maybe rephrase some of the sentences for the ease of read, and pay special attention to the words that will be used in different contexts. For example and speaking of the devil, I saw you translate "context" as متن in one of the paragraphs. It conveys the meaning adequately in _that sentence_, but might be misleading overall because "context" has a specific definition and place in the whole "deep learning latent space" :)

2020-10-21 06:28 UTC, telegraphroad commented on docs/fa/week12/12-1.md
> +**چرا این مدل خوب است؟**
Not to nitpick, but چرا این مدل این‌قدر خوب است might convey the extra emphasis here

2020-10-21 06:30 UTC, telegraphroad commented on docs/fa/week12/12-1.md
> +۱. ارتباط مستقیمی بین هر جفت کلمه ایجاد می کند. هر کلمه می تواند مستقیماً به حالت های پنهان کلمات قبلی دسترسی پیدا کند و گرادیان های ناپدید شده را کاهش دهد. تابع پرهزینه ای را به راحتی یاد می‌گیرد.
Wouldn't مشکل گرادیان‌های ناپدیدشونده را برطرف می‌کند make a bit more sense than کاهش می‌دهد? I mean they are already vanishing, right? :)

2020-10-21 06:32 UTC, telegraphroad commented on docs/fa/week12/12-1.md
> +- از برنامه زمانی نرخ یادگیری استفاده کنید: برای اینکه دگرگون سازها به خوبی کار کنند، باید سرعت یادگیری خود را از صفر تا هزار مرحله به صورت خطی کاهش دهید
I'd suggest using زمان‌بندی instead of برنامه‌ی زمانی

2020-10-21 06:35 UTC, telegraphroad commented on docs/fa/week12/12-1.md
> +ما محتمل ترین کلمه را در هر مرحله زمان می گیریم. با این وجود، هیچ تضمینی این محتمل ترین توالی ممکن باشد، زیرا اگر مجبور باشید در مرحله ای آن مرحله را انجام دهید، دیگر هیچ راهی برای پیگیری جستجوی خود
هیچ تضمینی برای این‌که این محتمل‌ترین توالی ممکن باشد وجود ندارد

2020-11-12 02:45 UTC, Atcold approved these changes
Merging for now. If a review is necessary, please open a new PR.

2020-11-12 02:47 UTC, merged