[BN] Beginning translations to Bengali
Atcold/pytorch-Deep-Learning pull request #677
Opened 2020-10-23 07:35 UTC by CodTan

Hi @Atcold!
This PR marks the beginning of translations of the materials to Bengali. 
In this PR, the `README-BN`.md and `index.md` have been translated to Bengali. Just let me know if things seem fine, or if any changes are required.

2020-11-12 02:50 UTC, Atcold requested changes
Please, update `docs/_config.yml`, and all the other `README.md` with the addition of the Bengali flag and link.

2020-11-12 02:50 UTC, Atcold commented on docs/bn/README-BN.md
> +[🇬🇧](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/README.md) &nbsp; [🇨🇳](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/zh/README-ZH.md) &nbsp; [🇰🇷](https://github.co
```suggestion
[🇬🇧](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/README.md) &nbsp; [🇨🇳](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/zh/README-ZH.md) &nbsp; [🇰🇷](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/ko/README-KO.md) &nbsp; [🇪🇸](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/es/README-ES.md) &nbsp; [🇮🇹](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/it/README-IT.md) &nbsp; [🇹🇷](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/tr/README-TR.md) &nbsp; [🇯🇵](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/ja/README-JA.md) &nbsp; [🇸🇦](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/ar/README-AR.md) &nbsp; [🇫🇷](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/fr/README-FR.md) &nbsp; [🇮🇷](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/fa/README-FA.md) &nbsp; [🇷🇺](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/ru/README-RU.md)  &nbsp; [🇧🇩](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/fr/README-BN.md)
```

2020-11-12 02:50 UTC, Atcold commented on docs/bn/index.md
> +</table>
There is week 15 now out!

2020-11-25 03:42 UTC, Atcold commented
Any update?

2020-12-08 10:21 UTC, CodTan commented
@Atcold , updated the suggested!

2020-12-11 05:47 UTC, merged