[FA] 12-1.md edit translation base on review
Atcold/pytorch-Deep-Learning pull request #690
Opened 2020-11-15 11:22 UTC by thisistayeb

2020-11-25 02:50 UTC, Atcold requested changes
I'm not sure I understand what's going on.
`12-2.md` was already translated at #673.

2020-11-25 02:50 UTC, Atcold commented on docs/fa/week12/12-1.md
> -translation-date: 10 Oct 2020
Why removing this?

2020-11-25 02:50 UTC, Atcold commented on docs/_config.yml
> +        - path: fa/week12/12-2.md
We already have this translation!

2020-11-29 17:53 UTC, thisistayeb commented on docs/_config.yml
> +        - path: fa/week12/12-2.md
I just edit some sentences.

2020-12-11 04:02 UTC, Atcold commented
No idea what's going on here.

2020-12-11 04:02 UTC, closed without merging