[KR] 13-3 Translation
Atcold/pytorch-Deep-Learning pull request #704
Opened 2020-12-04 03:03 UTC by shc443

2020-12-05 07:01 UTC, skyil7 requested changes
리뷰 완료했습니다. 업데이트 부탁드립니다~ 
번역 수고하셨습니다!

2020-12-11 04:03 UTC, Atcold commented
@shc443, any update?

2020-12-11 04:07 UTC, shc443 commented
Hello Alf!

I finished editing, and I was going to upload it by this weekend.

Let me know if that would work for you.

Have a good rest of your day, and talk to you soon.

Best,
Kevin

On Fri, Dec 11, 2020, 1:03 PM Alfredo Canziani <notifications@github.com>
wrote:

> @shc443
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shc443&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=8Tf1H9ksZe0S_DmWgz9wpf5NcXevLmYaVNe9Fz_zruA&s=cDzB1zV9P1P6Tc1TI4glblKwE4Kxzy9KVDf5NJ1F5cI&e=>,
> any update?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Atcold_pytorch-2DDeep-2DLearning_pull_704-23issuecomment-2D742953765&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=8Tf1H9ksZe0S_DmWgz9wpf5NcXevLmYaVNe9Fz_zruA&s=DZrmUvhblW3Pb0k7MDr7HQKdX9fllEtazSSnKNp_-ck&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHIZPAGE7JGPO7ZCKDPOXE3SUGKYRANCNFSM4UM3JOZA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=8Tf1H9ksZe0S_DmWgz9wpf5NcXevLmYaVNe9Fz_zruA&s=j8TESi6Qqe51eZYO4zq14F8WQmQ2GVSjzc4JywcYb-o&e=>
> .
>

2020-12-11 06:24 UTC, Atcold commented
Great! Let's have @skyil7 review it!

2020-12-11 07:08 UTC, skyil7 commented
Seems @shc443 doesn't upload the file yet.

I will merge this PR as soon as they are ready.

2020-12-13 22:23 UTC, Atcold commented
Oh, okay. Let's wait for @shc443 then 😀

2021-01-13 11:07 UTC, skyil7 approved these changes

2021-01-13 11:08 UTC, merged

2021-07-21 07:11 UTC, Atcold commented on docs/ko/week13/13-3.md
> +`update_all(message_func, reduce_func)` sends messages through all edges and updates all nodes.
This sentence has not been translated.

2021-07-21 07:15 UTC, Atcold commented
Also, there was no addition to `docs/_config.yml`, so this page was never actually displayed on the website.
Finally, here https://github.com/Atcold/pytorch-Deep-Learning/commit/2a1ac7c2e059f3c1e76f485a5775b658d6ff6893 I tried to fix all the issues I found. Please, have a look at https://atcold.github.io/pytorch-Deep-Learning/ko/week13/13-3/ and see if there are issues.

2021-07-22 06:08 UTC, shc443 commented
Hello Alf!

I am sorry for missing that part. Probably we missed it because we could
not check them on the website as you pointed out.

https://github.com/Atcold/pytorch-Deep-Learning/pull/792

I just edited the untranslated sentence and created a pr for that.

Hope you have a good rest of the day!

Best,
Kevin

On Wed, Jul 21, 2021 at 4:15 PM Alfredo Canziani ***@***.***>
wrote:

> Also, there was no addition to docs/_config.yml, so this page was never
> actually displayed on the website.
> Finally, here 2a1ac7c
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Atcold_pytorch-2DDeep-2DLearning_commit_2a1ac7c2e059f3c1e76f485a5775b658d6ff6893&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=ANPYQTmiAEBdrMKgYb4dcCIE9yMbm9m4IVEjFLViwKM&s=x_0FAQgK-RsMs5p-tYF71jKm41pudfTH4AFgJvqsHwo&e=>
> I tried to fix all the issues I found. Please, have a look at
> https://atcold.github.io/pytorch-Deep-Learning/ko/week13/13-3/
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__atcold.github.io_pytorch-2DDeep-2DLearning_ko_week13_13-2D3_&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=ANPYQTmiAEBdrMKgYb4dcCIE9yMbm9m4IVEjFLViwKM&s=MFNpp7d8V0rlhqdqMpxz8sLhJCRGJTkydMZKSd2Oz9k&e=>
> and see if there are issues.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Atcold_pytorch-2DDeep-2DLearning_pull_704-23issuecomment-2D883951231&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=ANPYQTmiAEBdrMKgYb4dcCIE9yMbm9m4IVEjFLViwKM&s=UA653Cg0NO-cuLq1k_UJtOEyPxvMJB_b5ldfI4_fGqE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHIZPAAW7O22W5AMYC6OZDTTYZXZDANCNFSM4UM3JOZA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=yjRmxMgqpL1pmEsR9zwBVg&m=ANPYQTmiAEBdrMKgYb4dcCIE9yMbm9m4IVEjFLViwKM&s=kbhEo90focv8gl85z9buoLTtr13nv7_wPGiixcK9rU0&e=>
> .
>