[BN] Translation of week 12-0
Atcold/pytorch-Deep-Learning pull request #730
Opened 2020-12-18 23:26 UTC by bhuiyanmobasshir94

Added the Bengali translation for week 12 and part 0. Also updated the config file path.

2020-12-18 23:46 UTC, Atcold approved these changes
Great, thanks!

2020-12-18 23:47 UTC, Atcold requested changes
Please, translate the title as well.

2020-12-18 23:47 UTC, Atcold commented on docs/bn/week12/12.md
> +title: Week 12
You forgot to translate the title.

2020-12-18 23:49 UTC, kishordgupta requested changes
সূচনা করব - is getting repeated,
How about use some synonom
Like  এরপর শুরু করব / তারপরে পরিচিত হব etc

2020-12-19 11:05 UTC, bhuiyanmobasshir94 commented on docs/bn/week12/12.md
> +title: Week 12
Ok sure

2020-12-19 19:02 UTC, kishordgupta approved these changes

2021-07-23 09:31 UTC, bhuiyanmobasshir94 commented
I think conflicts have been resolved here for this PR. Thank you.

2021-07-28 15:52 UTC, Atcold approved these changes
Great, thanks!

2021-07-28 15:52 UTC, merged