Update 12-3.md
Atcold/pytorch-Deep-Learning pull request #780
Opened 2021-05-06 07:22 UTC by PeppeSaccardi

Self-Attention Paragraph Typos: Issues #779

2021-05-06 13:03 UTC, Atcold requested changes
Translations will have 2 typos, in the English comment and in the translated text.
Please, fix both, so that there are no discrepancies.

Thanks!

2021-05-06 13:03 UTC, Atcold commented on docs/es/week12/12-3.md
>  <!-- where $\boldsymbol{a} \in \mathbb{R}^n$ is a column vector with components $\alpha_i$. -->
```suggestion
<!-- where $\boldsymbol{a} \in \mathbb{R}^t$ is a column vector with components $\alpha_i$. -->
```

2021-05-06 13:03 UTC, Atcold commented on docs/fr/week12/12-3.md
> +where $\boldsymbol{a} \in \mathbb{R}^t$ is a column vector with components $\alpha_i$.
This is the comment (which you correctly fixed), but you forgot to edit line 81 below.

2021-05-06 13:03 UTC, Atcold commented on docs/ja/week12/12-3.md
>  <!-- where $\boldsymbol{a} \in \mathbb{R}^n$ is a column vector with components $\alpha_i$. -->
```suggestion
<!-- where $\boldsymbol{a} \in \mathbb{R}^t$ is a column vector with components $\alpha_i$. -->
```

2021-05-06 13:54 UTC, PeppeSaccardi commented
Thanks @Atcold! Now everything should be fixed!

2021-05-07 23:56 UTC, Atcold approved these changes
Great! Thanks so much!

2021-05-07 23:56 UTC, merged