[PT] Adding weeks 03 to 06
Atcold/pytorch-Deep-Learning pull request #802
Opened 2021-11-15 04:49 UTC by leonsolon

[PT] First translation of weeks 03 to 06.

2021-11-19 21:57 UTC, Atcold requested changes
I cannot check what's going on if files are rewritten entirely.

![image](https://user-images.githubusercontent.com/2119355/142696582-78e934cf-1da7-4954-a0af-230b0b5a12a2.png)

Revert these changes, plz.

2021-11-19 21:57 UTC, Atcold commented on docs/pt/README-PT.md
> -[🇬🇧](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/README.md) &nbsp; [🇨🇳](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/zh/README-ZH.md) &nbsp; [🇰🇷](https://github.co
What happened here? Why the whole file has been rewritten?

2021-11-19 21:57 UTC, Atcold commented on docs/pt/index.md
> -    <tr>
Same here. What's going on?

2021-11-19 21:57 UTC, Atcold commented on docs/pt/week01/01-1.md
> -A história do aprendizado profundo remonta à um campo que mudou seu nome para cibernética agora. Começou na década de 1940 com McCulloch e Pitts. Eles tiveram essa ideia de que neurônios são unidades
What's going on?

2021-11-19 23:47 UTC, closed without merging

2021-11-19 23:48 UTC, leonsolon commented
I'll send another one with corrected files!

2021-11-20 00:03 UTC, Atcold commented
Oh, you could have simply sent a commit that was reverting those edits.

2021-11-20 00:33 UTC, leonsolon commented
I was afraid to mess with your repo :D

805 is correct! Finally :P

2021-12-03 20:03 UTC, Atcold commented
Okay, thanks.
No worries, I always check the PR content before merging.