[PT] Adding weeks 3 to 6
Atcold/pytorch-Deep-Learning pull request #805
Opened 2021-11-20 00:25 UTC by leonsolon

I've corrected the rewritten files. Sorry for the trouble! Good to go.

2021-12-03 20:55 UTC, Atcold requested changes
Wow, I just realised you sent a cumulative PR with other authors.
You need to add them to the commit using the `coauthor` field.
Also, see review feedback.

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week03/03-1.md
> +<div align="center">Figura 11. Modelo de Simon Thorpe de fluxo de informações visuais no cérebro<div>
Something is wrong here (and also in the English version).
The French version has the correct rendering.

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week03/lecture03.sbv
> +So if you take notes, make them pink. No, just kidding!
Uh… This is English?

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week03/practicum03.sbv
> +Alright. So again anytime you have no idea what's going on. Just stop me ask questions
More English…

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week05/lecture05.sbv
> +Aaron DeFazio he's a research scientist at Facebook working mostly on
English.

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week05/practicum05.sbv
> +one one column all right and so whenever we multiply these guys you can see these
English.

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week06/06-2.md
> + "
What is this?

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week06/06-3.md
> +### Rede Neural "Comum" * vs. * Redes Neurais Recorrentes
```suggestion
### Rede Neural "Comum" *vs.* Redes Neurais Recorrentes
```

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week06/lecture06.sbv
> +Which I haven't gone through last time
English.

2021-12-03 20:55 UTC, Atcold commented on docs/pt/week06/practicum06.sbv
> +the same things I wanted to talk today so I'm gonna go a bit faster please slow
English.

2022-02-18 18:27 UTC, Atcold commented
Any update on this?

2022-02-25 05:53 UTC, dsantiago commented
> Any update on this?



> Any update on this?

Maybe i can help here if others are too busy...

2022-02-25 05:58 UTC, Atcold commented
I believe you don't have writing access to @leonsolon's fork.

2022-02-25 06:26 UTC, dsantiago commented
If needed i can create one my own...

2022-03-13 01:44 UTC, leonsolon commented
Sorry for the delay! Let me know if there's anything left unfixed.

2022-04-25 15:29 UTC, merged

2022-04-25 15:29 UTC, Atcold commented
Awesome, thanks!